name: brown_brown
description: Open source alternative of 그린그린
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 # format DateTime
  collection: ^1.16.0

  # Database
  # floor: ^1.3.0
  sqflite: ^2.2.2
  image_picker: ^0.8.0
  path_provider: ^2.0.0
  uuid: ^3.0.0
  path: ^1.8.0

  # river pod
  flutter_riverpod: ^2.0.0
  riverpod_annotation: ^1.0.0

  # UI
  cupertino_icons: ^1.0.0
  google_fonts: ^3.0.0
  lottie: ^2.1.0
  flashy_tab_bar2: ^0.0.5
  fluttertoast: ^8.1.2
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.3.0
  build_runner: ^2.1.0
  riverpod_generator: ^1.0.0
  sqflite_common_ffi: ^2.2.0+1
  flutter_launcher_icons: "^0.11.0"

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"