import 'package:hive_flutter/hive_flutter.dart';

part 'tag_type.g.dart';

/// Background colors are generated by https://colorbrewer2.org
@HiveType(typeId: 2)
enum TagType {
  @HiveField(0)
  today(0xFFFFFFB3, '🌞오늘'),

  @HiveField(1)
  watering(0xFF80B1D3, '💦물'),

  @HiveField(2)
  feeding(0xFFBEBADA, '🍔비료'),

  @HiveField(3)
  potChanging(0xFFFB8072, '🪴분갈이'),

  @HiveField(4)
  newLeaf(0xFF8DD3C7, '🍃신엽'),

  @HiveField(5)
  flower(0xFFFDB462, '🌹개화'),

  @HiveField(6)
  suffering(0xFFB3DE69, '🐛병충해'),

  @HiveField(7)
  pesticide(0xFFFCCDE5, '🧪농약'),

  @HiveField(8)
  germinated(0xFFD9D9D9, '🌱발아'),

  @HiveField(9)
  seeding(0xFFBC80BD, '🚜파종'),

  @HiveField(10)
  rip(0xFF000000, '🪦쓰봉');

  // 0xFFCCEBC5
  // 0xFFFFED6F

  const TagType(this.color, this.translateKR);

  final int color;
  final String translateKR;
}
