name: brown_brown
description: Open source alternative of 그린그린
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 # format DateTime
  collection: ^1.17.0
  package_info_plus: ^4.0.1

  # i18n
  flutter_localizations:
    sdk: flutter

  # Image process
  flutter_image_compress: ^2.0.3

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.0

  # General
  image_picker: ^0.8.0
  path_provider: ^2.0.0
  path: ^1.8.0

  # river pod
  flutter_riverpod: ^2.0.0
  riverpod_annotation: ^2.1.1

  # UI
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.0
  google_fonts: ^4.0.4
  lottie: ^2.1.0
  fluttertoast: ^8.1.2
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.0
  riverpod_generator: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/lottie/
    # build info
    - ../.git/HEAD
    - ../.git/ORIG_HEAD
    - ../.git/refs/heads/

  fonts:
    - family: PoiretOne
      fonts:
        - asset: assets/fonts/PoiretOne-Regular.ttf
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NanumGothic-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/NanumGothic-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"